plugins { id 'com.android.application' }

android {
    namespace 'com.agrodominium.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.agrodominium.mobile.v3'
        minSdk 21
        targetSdk 35
        versionCode 31
        versionName '3.0.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
}
